/**
 * Realistic Indian college and professional seed data for development/demo purposes.
 * Clearly identified for testing and demonstrating platform capabilities.
 */

export const SAMPLE_STUDENTS = [
  {
    id: 'demo_student_1',
    fullName: 'Rahul Sharma',
    registerNo: '217101',
    email: 'rahul.sharma@psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    section: 'A',
    phone: '+91 98450 12345',
    skills: ['React', 'JavaScript', 'Node.js', 'Python', 'Tailwind CSS'],
    interests: ['Full Stack Development', 'Open Source', 'System Design'],
    bio: 'Aspiring Full Stack Engineer passionate about web technologies, cloud systems, and building developer tools.',
  },
  {
    id: 'demo_student_2',
    fullName: 'Ananya Krishnan',
    registerNo: '217102',
    email: 'ananya.k@psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Information Technology',
    year: '4th Year',
    section: 'B',
    phone: '+91 98450 23456',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Data Analysis'],
    interests: ['AI Research', 'Data Science', 'Product Analytics'],
    bio: 'Final year IT student focusing on predictive modeling, computer vision, and applied ML pipelines.',
  },
  {
    id: 'demo_student_3',
    fullName: 'Karthik Venkatesh',
    registerNo: '217103',
    email: 'karthik.v@psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Electronics & Communication',
    year: '3rd Year',
    section: 'A',
    phone: '+91 98450 34567',
    skills: ['C++', 'Embedded Systems', 'IoT', 'Python', 'Verilog'],
    interests: ['Robotics', 'VLSI Design', 'Hardware-Software Interfacing'],
    bio: 'ECE undergraduate passionate about IoT systems and edge computing.',
  },
  {
    id: 'demo_student_4',
    fullName: 'Sneha Patel',
    registerNo: '217104',
    email: 'sneha.patel@psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Computer Science & Engineering',
    year: '2nd Year',
    section: 'C',
    phone: '+91 98450 45678',
    skills: ['Java', 'Data Structures', 'Algorithms', 'SQL'],
    interests: ['Competitive Programming', 'Backend Engineering'],
    bio: '2nd year CSE student actively solving algorithmic challenges and learning scalable architecture.',
  },
  {
    id: 'demo_student_5',
    fullName: 'Aditya Verma',
    registerNo: '217105',
    email: 'aditya.v@psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Mechanical Engineering',
    year: '4th Year',
    section: 'A',
    phone: '+91 98450 56789',
    skills: ['SolidWorks', 'AutoCAD', 'ANSYS', 'Python', 'MATLAB'],
    interests: ['Automotive Engineering', 'Thermal Systems', 'Electric Vehicles'],
    bio: 'Mechanical engineer with a passion for sustainable mobility and EV drivetrain optimization.',
  },
  {
    id: 'demo_student_6',
    fullName: 'Divya Sundaram',
    registerNo: '217106',
    email: 'divya.s@psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Information Technology',
    year: '3rd Year',
    section: 'A',
    phone: '+91 98450 67890',
    skills: ['Figma', 'UI/UX Design', 'HTML/CSS', 'User Research', 'React'],
    interests: ['Product Design', 'Human-Computer Interaction', 'Design Systems'],
    bio: 'Passionate UI/UX designer crafting intuitive interfaces and cohesive digital experiences.',
  },
  {
    id: 'demo_student_7',
    fullName: 'Goutham Raj',
    registerNo: '217107',
    email: 'goutham.raj@psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Electrical Engineering',
    year: '4th Year',
    section: 'B',
    phone: '+91 98450 78901',
    skills: ['Power Systems', 'PLC', 'SCADA', 'MATLAB', 'Microcontrollers'],
    interests: ['Renewable Energy', 'Smart Grids', 'Industrial Automation'],
    bio: 'Focusing on clean energy transitions, grid modernization, and high-voltage power transmission.',
  },
  {
    id: 'demo_student_8',
    fullName: 'Meera Nambiar',
    registerNo: '217108',
    email: 'meera.n@psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Biotechnology',
    year: '3rd Year',
    section: 'A',
    phone: '+91 98450 89012',
    skills: ['Bioinformatics', 'Python', 'Genomics', 'Data Analysis', 'R'],
    interests: ['Computational Biology', 'Drug Discovery', 'Bioprocess Engineering'],
    bio: 'Bioengineering student enthusiastic about computational biology and health informatics.',
  },
];

export const SAMPLE_ALUMNI = [
  {
    id: 'demo_alumni_1',
    fullName: 'Priya Menon',
    email: 'priya.menon@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Computer Science & Engineering',
    graduationYear: '2018',
    company: 'Google',
    jobRole: 'Senior Product Manager',
    location: 'Bangalore, Karnataka',
    skills: ['Product Strategy', 'Roadmapping', 'Agile', 'User Analytics', 'Cloud Solutions'],
    experience: '6+ years in product management leading core search & enterprise developer tools.',
    linkedinUrl: 'https://linkedin.com/in/demo-priya-menon',
    phone: '+91 98111 00001',
    verificationStatus: 'verified',
    bio: 'Leading product initiatives for cloud developer platforms. Happy to mentor students on PM transition, interview prep, and career strategy.',
  },
  {
    id: 'demo_alumni_2',
    fullName: 'Arjun Sharma',
    email: 'arjun.sharma@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Information Technology',
    graduationYear: '2019',
    company: 'Microsoft',
    jobRole: 'Software Engineer III',
    location: 'Hyderabad, Telangana',
    skills: ['Distributed Systems', 'C#', '.NET Core', 'Azure', 'Kubernetes', 'Go'],
    experience: '5+ years building highly resilient cloud infrastructure and high-throughput microservices.',
    linkedinUrl: 'https://linkedin.com/in/demo-arjun-sharma',
    phone: '+91 98111 00002',
    verificationStatus: 'verified',
    bio: 'Backend systems engineer at Azure Core. Passionate about mentoring students in distributed systems and competitive coding.',
  },
  {
    id: 'demo_alumni_3',
    fullName: 'Kavya Rajan',
    email: 'kavya.rajan@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Computer Science & Engineering',
    graduationYear: '2017',
    company: 'Amazon',
    jobRole: 'Lead Data Scientist',
    location: 'Chennai, Tamil Nadu',
    skills: ['Machine Learning', 'Deep Learning', 'PyTorch', 'LLMs', 'Python', 'AWS SageMaker'],
    experience: '7+ years architecting ML pipelines, recommender engines, and NLP systems.',
    linkedinUrl: 'https://linkedin.com/in/demo-kavya-rajan',
    phone: '+91 98111 00003',
    verificationStatus: 'verified',
    bio: 'Specialized in scalable machine learning. Open to guiding students on research projects, resume audits, and ML roles.',
  },
  {
    id: 'demo_alumni_4',
    fullName: 'Rohit Nair',
    email: 'rohit.nair@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Electronics & Communication',
    graduationYear: '2016',
    company: 'Zoho Corporation',
    jobRole: 'Engineering Manager',
    location: 'Chennai, Tamil Nadu',
    skills: ['Team Leadership', 'Java', 'Full Stack', 'High Availability', 'Architecture'],
    experience: '8+ years scaling enterprise SaaS products serving millions of daily active users.',
    linkedinUrl: 'https://linkedin.com/in/demo-rohit-nair',
    phone: '+91 98111 00004',
    verificationStatus: 'verified',
    bio: 'Managing a team of 25+ engineers building cloud software. Keen to assist college students with placement preparation and referrals.',
  },
  {
    id: 'demo_alumni_5',
    fullName: 'Deepa Balasubramanian',
    email: 'deepa.b@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Information Technology',
    graduationYear: '2020',
    company: 'Atlassian',
    jobRole: 'Senior Frontend Engineer',
    location: 'Bangalore, Karnataka',
    skills: ['React', 'TypeScript', 'Next.js', 'Web Performance', 'Design Systems', 'GraphQL'],
    experience: '4+ years crafting accessible, high-performance web applications.',
    linkedinUrl: 'https://linkedin.com/in/demo-deepa-b',
    phone: '+91 98111 00005',
    verificationStatus: 'verified',
    bio: 'Frontend enthusiast dedicated to clean code and pixel-perfect design. Available for frontend portfolio reviews and interview coaching.',
  },
  {
    id: 'demo_alumni_6',
    fullName: 'Vikram Chandrasekhar',
    email: 'vikram.c@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Mechanical Engineering',
    graduationYear: '2015',
    company: 'Tesla',
    jobRole: 'Senior Mechanical Design Engineer',
    location: 'Pune, Maharashtra',
    skills: ['CAD/CAM', 'Thermal Analysis', 'GD&T', 'Manufacturing', 'SolidWorks'],
    experience: '9+ years in precision manufacturing and battery thermal management.',
    linkedinUrl: 'https://linkedin.com/in/demo-vikram-c',
    phone: '+91 98111 00006',
    verificationStatus: 'verified',
    bio: 'Passionate about mechanical innovations and electric vehicle powertrain design. Happy to mentor core engineering students.',
  },
  {
    id: 'demo_alumni_7',
    fullName: 'Harini Sundaresan',
    email: 'harini.s@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Computer Science & Engineering',
    graduationYear: '2021',
    company: 'Goldman Sachs',
    jobRole: 'Quantitative Analyst',
    location: 'Mumbai, Maharashtra',
    skills: ['Python', 'Quantitative Finance', 'Time Series', 'C++', 'Risk Modeling'],
    experience: '3+ years developing algorithmic risk frameworks and pricing engines.',
    linkedinUrl: 'https://linkedin.com/in/demo-harini-s',
    phone: '+91 98111 00007',
    verificationStatus: 'verified',
    bio: 'Working in quant finance and fintech. Guiding students interested in financial modeling, tech interviews in banking, and higher studies.',
  },
  {
    id: 'demo_alumni_8',
    fullName: 'Siddharth Raman',
    email: 'siddharth.r@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Electrical Engineering',
    graduationYear: '2018',
    company: 'Schneider Electric',
    jobRole: 'Power Systems Consultant',
    location: 'Coimbatore, Tamil Nadu',
    skills: ['Power Distribution', 'Energy Management', 'AutoCAD Electrical', 'IoT Automation'],
    experience: '6+ years designing smart grid systems and industrial power solutions.',
    linkedinUrl: 'https://linkedin.com/in/demo-siddharth-r',
    phone: '+91 98111 00008',
    verificationStatus: 'verified',
    bio: 'Consultant in power automation and green building technology. Eager to help electrical engineering students bridge the industry gap.',
  },
  {
    id: 'demo_alumni_9',
    fullName: 'Meenakshi Iyer',
    email: 'meenakshi.i@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Computer Science & Engineering',
    graduationYear: '2022',
    company: 'Flipkart',
    jobRole: 'Software Development Engineer',
    location: 'Bangalore, Karnataka',
    skills: ['Java', 'Spring Boot', 'Kafka', 'MySQL', 'System Architecture'],
    experience: '2+ years working on e-commerce checkout and order management microservices.',
    linkedinUrl: 'https://linkedin.com/in/demo-meenakshi-i',
    phone: '+91 98111 00009',
    verificationStatus: 'verified',
    bio: 'Recent graduate working in e-commerce backend engineering. Available to guide juniors on college placements, DSA practice, and internships.',
  },
  {
    id: 'demo_alumni_10',
    fullName: 'Aravind Swaminathan',
    email: 'aravind.s@alumni.psgtech.edu',
    college: 'PSG College of Technology',
    department: 'Information Technology',
    graduationYear: '2014',
    company: 'Adobe',
    jobRole: 'Principal Cloud Architect',
    location: 'Remote',
    skills: ['Cloud Architecture', 'DevOps', 'AWS', 'Kubernetes', 'Terraform', 'Security'],
    experience: '10+ years designing enterprise-scale cloud infrastructures and security frameworks.',
    linkedinUrl: 'https://linkedin.com/in/demo-aravind-s',
    phone: '+91 98111 00010',
    verificationStatus: 'verified',
    bio: 'Cloud architecture expert and tech speaker. Open for mentorship on cloud certifications, career long-term planning, and leadership.',
  },
];

export const SAMPLE_OPPORTUNITIES = [
  {
    title: 'Software Development Intern (Full Stack)',
    company: 'Zoho Corporation',
    type: 'Internship',
    workMode: 'On-site',
    location: 'Chennai, Tamil Nadu',
    description: 'Looking for enthusiastic 3rd and 4th year computer science students to join our core SaaS product team. You will work on real-world frontend applications using React and backend microservices in Java.',
    skills: ['React', 'JavaScript', 'Java', 'SQL'],
    deadline: '2026-10-15',
    externalLink: 'https://www.zoho.com/careers/',
    postedByName: 'Rohit Nair',
  },
  {
    title: 'Data Science & Analytics Intern',
    company: 'Amazon India',
    type: 'Internship',
    workMode: 'Hybrid',
    location: 'Bangalore, Karnataka',
    description: 'Work alongside lead data scientists to clean, analyze, and build predictive machine learning models on customer telemetry data.',
    skills: ['Python', 'SQL', 'Pandas', 'Machine Learning'],
    deadline: '2026-11-01',
    externalLink: 'https://amazon.jobs/',
    postedByName: 'Kavya Rajan',
  },
  {
    title: 'Associate Cloud Engineer (Alumni Referral)',
    company: 'Microsoft',
    type: 'Full-time',
    workMode: 'Hybrid',
    location: 'Hyderabad, Telangana',
    description: 'Direct referral opportunity for final-year students and recent graduates. Responsible for Azure cloud monitoring, automation scripts, and deployment pipelines.',
    skills: ['Azure', 'C#', 'PowerShell', 'Docker', 'CI/CD'],
    deadline: '2026-09-30',
    externalLink: 'https://careers.microsoft.com/',
    postedByName: 'Arjun Sharma',
  },
  {
    title: 'UI/UX Design Intern',
    company: 'Atlassian',
    type: 'Internship',
    workMode: 'Remote',
    location: 'Remote',
    description: 'Collaborate with global design teams to create design systems, wireframes, and prototypes for next-generation developer tooling.',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    deadline: '2026-10-30',
    externalLink: 'https://www.atlassian.com/company/careers',
    postedByName: 'Deepa Balasubramanian',
  },
  {
    title: 'Smart India Next-Gen Hackathon 2026',
    company: 'PSG Tech Innovation Hub & Google Cloud',
    type: 'Hackathon',
    workMode: 'Hybrid',
    location: 'Campus & Online',
    description: '36-hour flagship hackathon for student teams solving real-world challenges in AI, FinTech, Clean Energy, and Healthcare. Cash prizes up to ₹5,00,000 and direct internship interviews with alumni sponsors.',
    skills: ['AI/ML', 'React', 'Python', 'Cloud Solutions', 'System Design'],
    deadline: '2026-10-20',
    externalLink: 'https://hackathon.psgtech.edu',
    postedByName: 'Priya Menon',
  },
  {
    title: 'Junior Frontend Engineer Vacancy',
    company: 'Flipkart',
    type: 'Job Vacancy',
    workMode: 'On-site',
    location: 'Bangalore, Karnataka',
    description: 'Immediate vacancy for ambitious graduates with strong React and TypeScript background. You will join the Core Shopping Experience engineering team.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Redux', 'REST APIs'],
    deadline: '2026-11-15',
    externalLink: 'https://flipkartcareers.com',
    postedByName: 'Meenakshi Iyer',
  },
];

export const SAMPLE_EVENTS = [
  {
    title: 'Annual Global Alumni Meet 2026',
    description: 'Join hundreds of alumni, faculty, and graduating students for a memorable evening of networking, dinner, and celebrating our community achievements.',
    type: 'Alumni Meet',
    date: '2026-11-14',
    time: '06:00 PM',
    location: 'Campus Main Auditorium & Lawn, PSG College of Technology',
    meetingLink: '',
    registrationLink: 'https://forms.google.com/demo-alumni-meet-2026',
    organizer: 'Alumni Relations Cell & PSG Tech Management',
  },
  {
    title: 'Webinar: Navigating Tech Careers & Product Management',
    description: 'Interactive session hosted by alumni working at Google and Microsoft discussing roadmap planning, interview tactics, and shifting into product roles.',
    type: 'Webinar',
    date: '2026-09-20',
    time: '07:30 PM',
    location: 'Online',
    meetingLink: 'https://meet.google.com/demo-alumlink-webinar',
    registrationLink: 'https://forms.google.com/demo-tech-careers-webinar',
    organizer: 'CSE Alumni Association',
  },
  {
    title: 'Hands-on Workshop: Cloud Architecture & DevOps in Production',
    description: 'Learn modern Docker, Kubernetes, and automated CI/CD deployments directly from industry veterans.',
    type: 'Workshop',
    date: '2026-10-05',
    time: '10:00 AM',
    location: 'Computer Center Lab 3, Campus',
    meetingLink: '',
    registrationLink: 'https://forms.google.com/demo-cloud-devops-workshop',
    organizer: 'Department of Information Technology',
  },
  {
    title: 'AI & Generative Models Masterclass 2026',
    description: 'Explore state-of-the-art Large Language Models, fine-tuning techniques, and practical AI applications with lead research scientists.',
    type: 'Masterclass',
    date: '2026-10-25',
    time: '04:00 PM',
    location: 'Online',
    meetingLink: 'https://meet.google.com/demo-ai-masterclass',
    registrationLink: 'https://forms.google.com/demo-ai-masterclass',
    organizer: 'Data Science & AI Club',
  },
  {
    title: 'Entrepreneurship & Startup Incubation Panel',
    description: 'Hear from successful founder alumni on pitching to VCs, seed funding strategies, building initial MVP, and scaling tech startups.',
    type: 'Panel Discussion',
    date: '2026-11-02',
    time: '02:30 PM',
    location: 'GRD Auditorium, Campus',
    meetingLink: '',
    registrationLink: 'https://forms.google.com/demo-startup-panel',
    organizer: 'PSG Tech Entrepreneurship Cell',
  },
  {
    title: 'Executive Leadership & Placement Prep Bootcamp',
    description: 'A comprehensive weekend bootcamp focusing on technical interview prep, system design, salary negotiation, and resume optimization.',
    type: 'Bootcamp',
    date: '2026-11-20',
    time: '09:00 AM',
    location: 'Seminar Hall 2, Campus',
    meetingLink: '',
    registrationLink: 'https://forms.google.com/demo-placement-bootcamp',
    organizer: 'Placement & Career Development Cell',
  },
];

export const SAMPLE_ANNOUNCEMENTS = [
  {
    title: 'Welcome to AlumLink — The Official College Alumni Platform',
    content: 'We are thrilled to launch AlumLink for all students, alumni, and faculty of our institution. Build your profile, search the alumni directory, request mentorship, and explore verified career opportunities.',
    category: 'General',
    targetAudience: 'all',
  },
  {
    title: 'Alumni Mentorship Cohort 2026 Applications Open',
    content: 'Students in their 2nd, 3rd, and 4th years are encouraged to connect with verified alumni mentors for 1-on-1 resume reviews and technical interview preparations.',
    category: 'Career',
    targetAudience: 'student',
  },
  {
    title: 'Call for Alumni Speakers: Guest Lecture Series',
    content: 'Alumni interested in sharing domain insights or conducting interactive webinars for current students are invited to submit their session proposals through the portal.',
    category: 'Alumni',
    targetAudience: 'alumni',
  },
];
